# Generated by Django 5.2.7 on 2025-10-01 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=50, unique=True)),
                ('zone', models.CharField(choices=[('NEW', 'New Packs Zone'), ('FA', 'Failure Analysis Zone'), ('REPAIRED', 'Repaired Packs Zone'), ('SHIPPING', 'Shipping Zone')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('part_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IQC_PENDING', 'IQC Pending'), ('IN_STOCK', 'In Stock'), ('FA_PENDING', 'FA Pending'), ('FA_IN_PROGRESS', 'FA In Progress'), ('REPAIRED', 'Repaired'), ('EOL_TEST_PENDING', 'EOL Test Pending'), ('READY_TO_SHIP', 'Ready to Ship'), ('SHIPPED', 'Shipped')], default='NEW', max_length=20)),
                ('rma_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs', to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='FailureAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('lv_log_file', models.FileField(blank=True, null=True, upload_to='logs/lv/')),
                ('parsed_log_data', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('eol_test_passed', models.BooleanField(default=False)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pack')),
            ],
        ),
        migrations.CreateModel(
            name='PackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.pack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
